### ISSUE TITLE
매크로그래프 : 화웨이 클라우드 개발자 모집중.

### ISSUE THREAD

**Issue by khw7096** [lazypic/tdcourse#110]
- 전달 : 매크로그래프 이인호 대표님

**Comment by khw7096** [comment]
https://intl.huaweicloud.com/?locale=en-us

**Comment by baesy0** [comment]
오 화웨이 클라우드도 있구나

**Comment by baesy0** [comment]
클라우드 개발은 어떤걸 개발하는거에요?

**Comment by khw7096** [comment]
중국에 자체 렌더팜 관리툴을 만들고 운용하는 사업에 개발자가 필요하다고 하네요~

**Comment by niceinjeolmi** [comment]
중국어를 배운다....

**Comment by baesy0** [comment]
@niceinjeolmi 그래놓고 아랍어 배우면서..
